### ISSUE TITLE
pu2fa usage

### ISSUE THREAD

**Issue by alxsimon** [Paleogenomics/Chrom-Compare#2]
Hi,

I am trying to use pu2fa to produce pseudo-haploid sequences as proposed in this repository [https://github.com/nkschaefer/ad-libs](https://github.com/nkschaefer/ad-libs).

Could you please give me more information on the input format and the required arguments?

I tried something like
```
samtools mpileup -s -f [my reference] [my cram file] | pu2fa -
```
but the output is a lot of 
```
Incorrect number of bases read in: mg10_s00019  305364  A       0       *       *       *
```
without any fasta output.

A pileup file produced only with samtools command has this head
```
mg10_s00001     78      C       1       ^$.     4       $
mg10_s00001     79      C       1       .+1T    4       $
mg10_s00001     80      T       0       *       *       *
mg10_s00001     81      C       3       ...     FEF     $<.
mg10_s00001     82      A       3       ...     JFJ     $<.
mg10_s00001     83      T       3       ...     JFJ     $<.
mg10_s00001     84      T       3       ...     J<J     $<.
mg10_s00001     85      A       3       T..     JJJ     $<.
mg10_s00001     86      T       3       ...     JJJ     $<.
mg10_s00001     87      A       3       ...     JJJ     $<.
```

Thanks for your help!

**Comment by nkschaefer** [comment]
Hi - 

It looks like the way positions with zero coverage are reported in pileup output changed from one samtools version to another. I've added code that should handle the new way these positions are reported in pileup output -- so give the new version a try and let us know if it's still not working.

Thanks,
Nathan

**Comment by alxsimon** [comment]
Thank you for your answer.
Your fix does indeed remove the error message, unfortunately I do not manage to obtain any output from the program.

I think the default parameters should give me some output even if my data is low coverage, please find attached a subset of a pileup file I am trying to convert.
[test.pu.gz](https://github.com/Paleogenomics/Chrom-Compare/files/3488732/test.pu.gz)

There is no output to the stdout coming from the command `pu2fa test.pu`

**Comment by nkschaefer** [comment]
Since pileup output can be huge (and thus not always a good idea to save to a file), pu2fa takes pileup output from stdin, so you can pipe directly from samtools mpileup if you want. I had a look, and running it this way:
zcat test.pu.gz | Chrom-Compare/pu2fa -c mg10_s00001
seems to work. If you run it with no arguments, you'll see the list of options to filter by quality and coverage.

**Comment by alxsimon** [comment]
Ok I get it now, the -c option is required for this to work.

The only way I have an output is by using:
`samtools mpileup -s -f [my ref] -r mg10_s00001 [my bam] | pu2fa -c mg10_s00001`

So if I get it correctly we need to loop on all the contigs we want to output, as this tool is not designed to process a complete pileup file.

Thank you very much for your help.

**Comment by edgreen72** [comment]
Yes, that's right. Could you open a github issue to add better
documentation of this?
